name: Daily arXiv Fetcher

on:
  schedule:
    # 毎日 日本時間の朝7:29（UTCの午前0:00）に実行
    - cron: '29 22 * * *'
  workflow_dispatch: # 手動でいつでも実行できるようにするボタンを追加

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: コードをチェックアウト
      uses: actions/checkout@v4

    - name: Python環境のセットアップ
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: ライブラリのインストール
      run: |
        pip install arxiv requests deep-translator typer

    - name: QA関連論文の取得とDiscord通知
      env:
        DISCORD_WEBHOOK_URL_QA: ${{ secrets.DISCORD_WEBHOOK_URL_QA }}
      run: |
        for i in 1 2 3 4 5; do
          python fetch_arxiv.py \
            -k quantum \
            -k annealing \
            -k optimization \
            -w "${DISCORD_WEBHOOK_URL_QA}" && exit 0
          echo "Retry $i failed. Waiting..."
          sleep $((i * 90))
        done
        exit 1

    - name: Pruning関連論文の取得とDiscord通知
      env:
        DISCORD_WEBHOOK_URL_PRUNE: ${{ secrets.DISCORD_WEBHOOK_URL_PRUNE }}
      run: |
        for i in 1 2 3 4 5; do
          python fetch_arxiv.py \
            -k pruning \
            -w "${DISCORD_WEBHOOK_URL_PRUNE}" && exit 0
          echo "Retry $i failed. Waiting..."
          sleep $((i * 90))
        done
        exit 1

    - name: Quantization関連論文の取得とDiscord通知
      env:
        DISCORD_WEBHOOK_URL_QUANTIZATION: ${{ secrets.DISCORD_WEBHOOK_URL_QUANTIZATION }}
      run: |
        for i in 1 2 3 4 5; do
          python fetch_arxiv.py \
            -k quantization \
            -w "${DISCORD_WEBHOOK_URL_QUANTIZATION}" && exit 0
          echo "Retry $i failed. Waiting..."
          sleep $((i * 90))
        done
        exit 1